version: '3'
services:
  server:
    container_name: charter_server
    image: 918308541697.dkr.ecr.eu-central-1.amazonaws.com/charter-service:latest
    restart: always
    environment:
      - spring.profiles.active=dev
  client:
    container_name: charter_client
    image: 918308541697.dkr.ecr.eu-central-1.amazonaws.com/charter-client:latest
    depends_on:
      - server
    restart: always
  proxy:
    image: nginx:latest
    container_name: charter_proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl/
    environment:
      - TZ=Europe/Warsaw
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - client
    restart: always
